### ISSUE TITLE
Glyph overlap issue with USE

### ISSUE THREAD

**Issue by khaledhosny** [notofonts/sinhala#1]
### Glyph overlap issue 
The version of Noto Sans Sinhala from this repository have some glyph overlaps issue, compared to the version from https://fonts.google.com/noto/specimen/Noto+Sans+Sinhala when shaped with USE.

### Font 
NotoSansSinhala/unhinted/ttf/NotoSansSinhala-Regular.ttf

### Where the font came from, and when
https://github.com/notofonts/sinhala/releases/tag/NotoSansSinhala-v2.005

### Issue
With HarfBuzz >= 4.4.0 (where Sinhala is shaped through USE) and the font from the repo:
```
hb-view NotoSansSinhala/unhinted/variable-ttf/NotoSansSinhala\[wdth\,wght\].ttf "ශ්‍රී ලංකාවේ ප්‍රධාන ජාතිය"
```
![](https://user-images.githubusercontent.com/93914/179292584-14a90c45-6ca7-4b0f-8747-7b7654046384.png)

Compared to the font from GF:
```
hb-view Noto_Sans_Sinhala/NotoSansSinhala-VariableFont_wdth\,wght.ttf"ශ්‍රී ලංකාවේ ප්‍රධාන ජාතිය"
```
![](https://user-images.githubusercontent.com/93914/179292927-855dd068-3be4-4d79-8c60-3222cb57d535.png)

DirectWrite output is similar to HarfBuzz in both cases.

**Comment by khaledhosny** [comment]
I found this while debugging https://github.com/harfbuzz/harfbuzz/issues/3725

**Comment by simoncozens** [comment]
The obvious big-hammer fix would be to reclassify the spacing marks as bases, to stop the width zeroing. We really want to be able to support both USE and pre-USE shapers.

**Comment by simoncozens** [comment]
I've fixed this by making them all bases.
