### ISSUE TITLE
Sinhala: sub-optimal placement of repaya in complex conjunct

### ISSUE THREAD

**Issue by mjansche** [notofonts/sinhala#4]
In the word ආර්‍ය්‍ය, the repaya glyph is currently being placed above the yansaya glyph. It would be better to place it immediately above the consonant that logically follows repaya (i.e. the full ya glyph). Perhaps this is best illustrated by the output of hb-view from the HarfBuzz master branch. Here is how the text ආර්‍ය්‍ය (0D86 aa; 0DBB 0DCA 200D repaya; 0DBA ya; 0DCA 200D 0DBA yansaya) renders in NotoSansSinhala-Regular.ttf (md5sum: b177716c7ff95c385902dba9d3b0b5ad):

![aaryya_noto](https://cloud.githubusercontent.com/assets/11460451/10171825/f2790fa4-66d3-11e5-9e8b-8d32efdc5bb7.png)

Compare this with how the same text is rendered with the LKLUG Sinhala font (e.g. in Debian/Ubuntu package fonts-lklug-sinhala; md5sum: 96b2f06cf1cf4e436ec46198d4bc61f2):

![aaryya_lklug](https://cloud.githubusercontent.com/assets/11460451/10171662/173067d0-66d3-11e5-8571-c4fa119610fd.png)

According to one native speaker, both renderings are understandable but the LKLUG rendering is preferred.

**Comment by simoncozens** [comment]
Just in case this comes up again in the future: The behaviour is different based on whether the font is processed with the Indic shaper (Harfbuzz <= 4.3.0) or the USE shaper (Harfbuzz >= 4.4.0). The new behaviour is correct (yareph/virama instead of yahalant/reph).

**Comment by simoncozens** [comment]
There is currently a difference between Sans and Serif renderings.

**Comment by JelleBosmaMT** [comment]
> There is currently a difference between Sans and Serif renderings.

In the designer approved version, the only difference in the GSUBs of Sans and Serif is in the rendering of Ra with the ae and aae vowel-signs: sans uses a contextual vowel, serif uses a ligature.

**Comment by simoncozens** [comment]
> There is currently a difference between Sans and Serif renderings.

I was wrong about this; I just rebuilt the font and it's fine.
